version: '3'

vars:
  DEPLOY_DIR: deployment
  GLOBAL_ENV: "{{.DEPLOY_DIR}}/.env"

tasks:
  default:
    desc: "Показать доступные команды"
    cmds:
      - task -l

  infra:up:
    desc: "Поднять всю локальную инфраструктуру"
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose up -d
      - echo "==> Инфраструктура успешно запущена!"

  infra:down:
    desc: "Остановить и удалить контейнеры инфраструктуры"
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose down

  run:
    desc: Run a service
    summary: |
      Запускает указанный сервис с пробросом переменных из /deployment/{{.SERVICE}}/.env
    cmds:
      - task: service:run
        vars: { SERVICE: '{{.SERVICE}}' }

  service:run:
    internal: true
    dir: 'services/{{.SERVICE}}'
    cmds:
      - go run ./cmd/app

  api:install-tools:
    desc: "Установить/обновить утилиты для генерации API (oapi-codegen)"
    cmds:
      - echo "==> Установка github.com/oapi-codegen/oapi-codegen/v2..."
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - echo "==> Готово!"

  api:generate:
    desc: "Сгенерировать Go-код из OpenAPI (пример: task api:generate SERVICE=inbound-connector)"
    summary: |
      Генерирует серверный интерфейс, модели и клиенты на основе OpenAPI спецификации.
      Берет конфигурацию из shared/api/{{.SERVICE}}/v1/oapi-codegen.yaml
    dir: 'shared/api/{{.SERVICE}}/v1'
    requires:
      vars: [SERVICE]
    cmds:
      - echo "==> Генерация API для сервиса {{.SERVICE}}..."
      - oapi-codegen -config oapi-codegen.yaml openapi.yaml
      - echo "==> Успешно сгенерировано в pkg/api/{{.SERVICE}}/v1!"

  api:gen-inbound:
    desc: "Генерация API для inbound-connector"
    cmds:
      - task: api:generate
        vars: { SERVICE: 'inbound-connector' }