version: '3'

vars:
  DEPLOY_DIR: deployment
  GLOBAL_ENV: "{{.DEPLOY_DIR}}/.env"

tasks:
  default:
    desc: "Показать доступные команды"
    cmds:
      - task -l

  infra:up:
    desc: "Поднять всю локальную инфраструктуру"
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose up -d
      - echo "==> Инфраструктура успешно запущена!"

  infra:down:
    desc: "Остановить и удалить контейнеры инфраструктуры"
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose down

  run:
    desc: Run a service
    summary: |
      Запускает указанный сервис с пробросом переменных из /deployment/{{.SERVICE}}/.env
    cmds:
      - task: service:run
        vars: { SERVICE: '{{.SERVICE}}' }

  service:run:
    internal: true
    dir: 'services/{{.SERVICE}}'
    cmds:
      - go run ./cmd/app