services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ${COMPOSE_PROJECT_NAME}-jaeger
    env_file:
      - .env
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "${JAEGER_UI_PORT:-16686}:16686"   # UI для просмотра трейсов

    networks:
      - esb_network