services:
  inbound-connector:
    build:
      context: ../..
      dockerfile: deployment/inbound-connector/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-inbound-connector
    env_file:
      - .env
    working_dir: /app
    networks:
      - esb_network
    depends_on:
      otel-collector:
        condition: service_started
