apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-esb
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger-esb

  - name: Jaeger
    type: jaeger
    uid: jaeger-esb
    access: proxy
    url: http://jaeger:16686